[workspace]
members = [
    'runtime',
    'node',
]

[profile.release]
panic = 'unwind'


[patch.crates-io]
# We use a custom EVM which support "environmental tracing". The patch allow to force usage of
# this crate version in all transitive dependencies (frontier).
# This will be necessary as long as frontier don't depend on this crate version.
evm = { git = "https://github.com/PureStake/evm", branch = "jeremy-environmental-hook", default-features = false, features = ["with-codec", "tracing"] }
evm-runtime = { git = "https://github.com/PureStake/evm", branch = "jeremy-environmental-hook", default-features = false, features = ["tracing"] }
evm-core = { git = "https://github.com/PureStake/evm", branch = "jeremy-environmental-hook", default-features = false, features = ["with-codec", "tracing"] }
evm-gasometer = { git = "https://github.com/PureStake/evm", branch = "jeremy-environmental-hook", default-features = false, features = ["tracing"] }