[package]
authors = ["PureStake"]
edition = "2018"
name = "token-factory"
version = "0.1.0"

[dependencies]
ethereum-types = { version = "0.11.0", default-features = false }
fp-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "v0.6-moonbeam" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
hex-literal = { version = "0.3.1" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-ethereum = { git = "https://github.com/purestake/frontier", default-features = false, branch = "v0.6-moonbeam" }
pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "v0.6-moonbeam" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
rustc-hex = { version = "2.1.0", default-features = false }
serde = { version = "1.0.101", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }

[features]
default = ["std"]
std = [
    "ethereum-types/std",
    "parity-scale-codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-ethereum/std",
    "pallet-evm/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "rustc-hex/std",
    "serde",
    "sp-runtime/std",
    "sp-std/std",
    "sp-core/std",
    "sp-io/std",
]